name: ✨ Feature Request
description: Suggest a new feature for fuzzygit.
title: "[Feature]: "
labels: ["feature", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving fuzzygit! Please provide the following details.
  - type: input
    id: feature-title
    attributes:
      label: 📝 Feature Title
      description: What is the title of your feature request?
      placeholder: ex. Enhanced Logging
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 💬 Feature Description
      description: Please describe the feature you would like to see and why.
      placeholder: Describe the feature...
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority Level
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true
